name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Check wasm-pack version
        run: wasm-pack --version

      - name: Build WASM
        run: |
          echo "Running wasm-pack build..."
          wasm-pack build --target web
          echo "Listing pkg directory:"
          ls -la pkg
          if [ ! -f pkg/rust_wasm_graphics.js ]; then
            echo "ERROR: rust_wasm_graphics.js not found. Build failed."
            exit 1
          fi

      - name: Prepare deployment directory
        run: |
          mkdir dist
          cp index.html dist/
          cp -r pkg dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
